### PR TITLE
Update example installation instructions in docs

### LINKED ISSUE #465: Conflict HydroMT version vs examples version
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are wrong

### Location of the documentation

https://deltares.github.io/hydromt/latest/getting_started/examples_index.html

### Documentation problem

In the docs, we asked the user to usually install hydromt with conda-forge.
But then to run the examples, we advise to clone the current dev version of the repository in order to download the jupyter notebooks.

Depending on changes (especially before releasing), the content in the examples might not work with the latest conda-release so examples would fail.
This has been reported for hydromt-wflow: https://jmp75.github.io/work-blog/

### Suggested fix for documentation

At least in the docs mention that users should download the zip folder from the hydromt release version they are using or warn that if they use main/clone they may run into problems.

Not sure if we could publish our examples more smartly, with maybe a function that would check the current installed hydromt version and downloads the right examples from there?

### LINKED ISSUE #546: Installation guide for examples is not up-to-date
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are wrong

### Location of the documentation

https://deltares.github.io/hydromt/latest/getting_started/examples_index.html

### Documentation problem

With make.py, the environment.yml file does not exist anymore so the recommended installation does not work anymore.

Related issue:
https://github.com/Deltares/hydromt_wflow/issues/206

### Suggested fix for documentation

Either update by explaining how to install and use make and add the tomli dependency.

Or do create maybe in the examples folder the correct environment.yml file (maybe can be automatically created in one of our github workflow?).
I still think that for most hydromt users who works with command line and are less handy with python, we should not complicate things too much, especially when it comes to installing and trying out the tool for the first time. So I would be in favor of the second option

### PR DESCRIPTION
**Pull request by savente93**
## Issue addressed
Fixes #546 
Fixes #465 

## Explanation
I've decided to solve both of the issues above by simply explaining in the examples that either you need a dev installation for the latest examples, or you should check out the examples of the version you have installed. I have done this for a couple of reasons:
1. if you want to run the examples you already need the repository, at which point, making a dev install is a small step beyond that
2. given that you already have the repo, we can assume the user has at least some very rudimentary git knowledge, so checking out the tag of the version installed which has the versions of the examples they want is a simple operations
3. We also have binder for running the examples. 
4. it is by far the simplest option on our side. 

## Checklist
- [x] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [x] Updated documentation if needed
- [x] Updated changelog.rst if needed

## Additional Notes (optional)
One other thing we could do is make the documentation link we list point to the latest stable release instead of the latest/dev version. That way people will find the examples that should be compatible with the versions they install from conda/pip. This would require a slight adjustment in how the docs are generated so I'll leave that for another issue/PR to figure out if that is something we want, but I did want to bring up the idea at least.

### CODE REVIEW

**Comment by DirkEilander** [comment]
> One other thing we could do is make the documentation link we list point to the latest stable release instead of the latest/dev version. That way people will find the examples that should be compatible with the versions they install from conda/pip. This would require a slight adjustment in how the docs are generated so I'll leave that for another issue/PR to figure out if that is something we want, but I did want to bring up the idea at least

This is not bad idea! I think it can be done by changing the link in [index.html](https://github.com/Deltares/hydromt/blob/gh-pages/index.html) in the `gh-pages` branch to point to "stable" rather than "latest".

**Comment by DirkEilander** [comment]
I'm happy for these changes to be merged. Whether it solves #465 satisfactory I'll leave up to @hboisgon We can just see what feedback we get after these changes (and changing the docs landing page) before we put more work into this following the suggestion in that issue.

**Review by DirkEilander — APPROVED** [review]
I'm happy for these changes to be merged. Whether it solves https://github.com/Deltares/hydromt/issues/465 satisfactory I'll leave up to @hboisgon We can just see what feedback we get after these changes (and changing the docs landing page) before we put more work into this following the suggestion in that issue.

**Comment by hboisgon** [comment]
I still think the new explanations are not fully clear. Most of our users are command line users I think so as examples is one of the first thing they look at, everything should be clear step by step copy pasting and not going from one page to the other. There was also some spelling mistakes. I'll open a new branch to correct it.

**Pull request merged**
