### PR TITLE
Rivers

### PR DESCRIPTION
**Pull request by DirkEilander**
- gis_utils.nearest and gis_utils.nearest_merge methods to merge GeoDataFrame based on proximity
- river_width to estimate a segment average river width based on a river mask raster 
- river_depth to get segment average river depth estimates based bankfull discharge (requires pyflwdir v0.5.2 - to be realeased)
- flw.floodplain_elevation method which returns floodplain classification and hydrologically adjusted elevation

### CODE REVIEW

**Comment by hboisgon** [comment]
Nice changes! Is the idea that in the end we fully move the river.py workflow out of hydromt_wflow into hydromt core? If maybe good to transfer the functions now already?

**Review by hboisgon — APPROVED** [review]
Nice and useful to get river depth estimations! 
Very minor but could you also list the new functions in the docs? And add the new geopandas min version also in the environment.yml files? Just so that they all match.
Thanks a lot!

**Comment by DirkEilander** [comment]
Thanks for the review @hboisgon. 

I've made the changes you requested to the docs and env files. Also bumped pyflwdir which was released on conda-forge this morning and is required for the flwdir.river_depth method.

I've put the general parts of the river methods here. Both hydromt_wflow and hydromt_sfincs will have slightly different implementations.

**Comment by hboisgon** [comment]
Perfect! Sounds good to go then @DirkEilander

**Comment by DirkEilander** [comment]
@hboisgon Added one more method in in hydromt.flw which requires a release of pyflwdir. Will merge after that release. Let me know if you have suggestions on that method.

**Pull request merged**
