### PR TITLE
Improve reproducibility dd

### LINKED ISSUE #356: DOC: better document in the data catalogs if datasets were pre-processed
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Location of the documentation

In the docs here: https://deltares.github.io/hydromt/latest/user_guide/data_existing_cat.html
Maybe also here (meta section) depending on implementation: https://deltares.github.io/hydromt/latest/user_guide/data_prepare_cat.html

### Documentation problem

Some of the datasets in the pre-defined catalogs are actually not original but pre-processed data (eg. modis_lai, merit_hydro for some of the layers etc).
Maybe we should find a standard way of letting the user know about this?
See also issue in [hydromt-wflow:#157](https://github.com/Deltares/hydromt_wflow/issues/157)

Known issues:

- merit_hydro
- merit_hydro_patch
- modis_lai
- era5 other than hourly (daily, zarr)
- chirps

Possibly related:
- hydro_lakes
- hydro_reservoirs

### Suggested fix for documentation

I think so far we tried to use source_url and notes in meta to say if processing was done. For some data sources it's missing but I also wonder if this way is clear to the user or if we should do it differently ?

For example only add source_url if no processing was done.
In case of processing, use new keywords processing_from_url, processing_from_doi, processing_steps?

### PR DESCRIPTION
**Pull request by Tjalling-dejong**
## Issue addressed
Fixes #356  #521 and partially #537

## Explanation
This PR updates the deltares data catalog to include new features such as versions/variants of data sources. Also if a data source has been pre-processed the path to the pre-processing script or the notes describing the pre-processing is included. 
In addition I added the temporal extent of the datasets with a temporal dimension.

## Checklist
- [x] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [x] Updated documentation if needed
- [x] Updated changelog.rst if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Review by savente93 — APPROVED** [review]
Nice work Tjalling. It would be nice if we can also add the spatial extent and also host the pre-processing scripts we now have locally (I assume on the P drive) somewhere but these can be separate issues I think, so we can merge this for now.

**Comment by DirkEilander** [comment]
Thanks for this work @Tjalling-dejong! Unfortunately this PR got merged too soon I think seeing some comments on Teams. This change directly affects all users and we need to think about how to properly test it.

**Comment by Tjalling-dejong** [comment]
I replicated the error with the soilgrids dataset that people have raised in the HydroMT chat. The error persists in earlier versions of the data catalog as well. What has changed with this PR is that I added versions to data catalog items. With this change the users are served the latest version of a dataset by default. Thus, the soilgrids dataset given to the users is the latest, namely soilgrids_v2.0. This version of the dataset also breaks in earlier versions of the data catalog.

Error can be replicated with `datacatalog.get_rasterdataset("soilgrids_v2.0")`.

**Comment by Tjalling-dejong** [comment]
I have made an issue regarding the error with soilgrids_v2.0 dataset (#706).

**Comment by DirkEilander** [comment]
Thanks for checking this issue @Tjalling-dejong 👍 

The issue was indeed not caused by this PR, but we do change the default dataset as you already mention. I think it would be good to:
1) have a small test that only runs locally to actually reads (a random slice of) all the datasets in the catalog
2) keep track and communicate for which datasets the default version changes when we publish. Perhaps we can also add a note in the meta data of the items like `updated_in_version: xx`
3) make it common practice to add the version of your dataset in your hydromt scripts / model builder yml files (for discussion in the next plugin meeting @alimeshgi)

Would it be possible to add point 1 to this PR? And let's discuss about point 2.

**Pull request merged**
