### PR TITLE
cli data_libs fix

### PR DESCRIPTION
**Pull request by DirkEilander**
* fixes use of  single path without list notation in data_libs in config [global] section. To behaviour is now also similar to --deltares-data which overwrites the setting in the ini file.
* small fix of erroneous version number. This should solve the issue with the wrong folder name in the gh-pages branch.

### CODE REVIEW

**Comment by DirkEilander** [comment]
@hboisgon Just a very small PR. If all you agree it can be merged with main and the branch deleted.

**Comment by DirkEilander** [comment]
after discussion with @hboisgon 

The following config notations with multiple and single files should both work. We need to double check if the first notation still works with this PR.

```
[global]
data_libs = ['relative/path/to/some_file.yml', '/absolute/path/to/another/file.yml']
```

```
[global]
data_libs = 'relative/path/to/some_file.yml'
```

**Comment by DirkEilander** [comment]
I've checked and both notations below work now. 

> 
> ```
> [global]
> data_libs = ['relative/path/to/some_file.yml', '/absolute/path/to/another/file.yml']
> ```
> 
> ```
> [global]
> data_libs = 'relative/path/to/some_file.yml'
> ```

PS Would be good to create a dummy model in the conftest.py and add this to the entrypoints (using a monkeypatch?) such that it called from command line. That would make it possible to extent the tests on the cli interface and check if this behavior.

**Review by hboisgon — APPROVED** [review]
Thanks for the checks! And agree to give priority to the CLI instead of a mix of cli+config for data_libs options

**Pull request merged**
