### PR TITLE
ENH: Add Dockerfile 

### LINKED ISSUE #248: Deploy HydroMT docker image to dockerhub

### PR DESCRIPTION
**Pull request by savente93**
Doesn't quite resolve  #248 but makes a significant step. Once this gets merged we can star looking at publishing the image. Wasn't quite sure what the use case was going to be (although it's sure to be useful for cloud integration) so for now it's just a minimal image. We can always add more parts if necessary

### CODE REVIEW

**Comment by DirkEilander** [comment]
@Jaapel Could you review this?
It would also be nice to explore how we can use this file to deploy a docker image to docker hub (could be done in a different PR).

**Comment by savente93** [comment]
I've added a github action to deploy the docker image to dockerhub. not sure whether we need to configure credentials for the deltares dockerhub account, but baring that it should work. I tested it with my own dockerhub account and that went fine.

**Comment by Jaapel** [comment]
Nice work @savente93.
What I would add is a mechanism to consistently tag the image with the HydroMT version.
I think the tag is `deltares/hydromt`, which I believe will push to latest. We run this workflow when releasing, so it is best to tag is with the release tag.

**Comment by savente93** [comment]
Like so?

**Pull request merged**
