### PR TITLE
Restructure envs

### LINKED ISSUE #394: Environment should be restructured.
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

:

### Current behaviour

Currently the environment specifications (e.g. all/doc/test) are not structured very well and this needs a bit of an overhaul so other applications can be more targeted in what they need. Some specs that would probably be useful: 
- tests
- examples/jupyter/binder
- cli/dev
- env
- min
- mesh

Feel free to edit as necessary

### Desired behaviour

The environments are better specified so they have fewer overlap and systems can target more specifically what they need. 

### Additional context

Been running into this a lot when trying to restructure the Dockerfile for the various use-cases.

### PR DESCRIPTION
**Pull request by savente93**
## Issue addressed
Fixes #394 

## Explanation
This is a fairly big one so the explanation is going to be a bit longer. Since it also touches on multiple areas, I'll request reviews from multiple people though not all of them have to review all of it. I'll mark each section for the appropriate reviewer.

### Structure of the environments [Dirk/Helene]
There are two concepts here that I've used to structure the dependencies: 
1. groups are "logical" clusters of dependencies that are necessary for each other to function. They are meant to be modular, optional and independent. the ones I've landed on are: 
   a. `io` Reading and writing various formats like excel but also  cloud file systems
   b. `extra` Couldn't think of a better name for this one, but it has some extra for ET and mesh calculations
   c. `dev` everything you need to develop and publish HydroMT
   d. `test` What you need to run the test suite. Test suite should be setup that only tests that use the dependencies that are installed are run, so this should always pass no matter what other dependencies you may or may not have installed.
   e. `doc` generate the docs
   f. `jupyter` Run Jupyter notebooks and run the examples. Going to use this for binder support mostly.
   g. `deprecated`  dependencies that we hope to remove soon, but aren't quite ready to yet. 
2. "flavors" are more or less just collections of one or more groups designed for common use cases. The flavors are: 
  a. `min` no optional dependencies. mostly as a base to build your DIY stack on. 
  b. `slim` Just the operational bits, what most people will probably want and what the cloud will most likely use 
  c. `full`  absolutely everything, useful for developing. 

Of all the combinations I tried I think this strikes the best balance between being fully featured without being bloated for each use case. This was particularly important for the docker images which I'll talk about below. 

### Env management [Jaap/Dirk/Helene]
To manage everything I've started making more use of the make file to keep it all somewhat easy. The docker bits are mostly for me to make sure I (and the CI) don't accidentally build the docker images and the corresponding environments. What might be more useful for users is the `make env` or `make dev` receipts. the `dev` receipt is meant to be an easy way to set up everything you need to get coding.  ( I also use this frequently as well). The `make env` gives a more fine grained access to building the correct environments and can be used to address the groups directly like so `make env OPT_DEPS="extra,io,docs"`. By default it uses micromamba, but you can also adjust that like so `make env PY_ENV_MANAGER='mamba'`. If you do this frequently, you can set it as an environment variable in your shell and it should just pick up on it as well. 

### Docker images [Jaap]

Took quite some finagling, and I went through many different setups, but I managed to get all of the images around 2 GB which I'm really pleased by. I've made docker images for each of the "flavours" (see above). I think these will be good for most use cases. In particular this (in addition to the docs cleanup I did) should make binder much faster to startup. The statements are laid-out to maximize cache hits when only code changes, which will be useful as I intend to use these images to speedup the testing CI as well, but that's a story for another PR. 

(I'll add all of this to the docs as well) 
 

## Checklist
- [x] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [x] Updated documentation if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Comment by savente93** [comment]
Fixes #403

**Comment by savente93** [comment]
Fixes #406

**Comment by savente93** [comment]
I've also taken the opportunity to fix a few small doc mistakes why I was at it.

**Comment by savente93** [comment]
Thanks! If I remember correctly, they were optional dependencies in a category called "all" which is why they are still optional now. I just didn't want to call it call because I thought that would be confusing with the `full` flavour. I'm happy to add them to the main dependencies, and just get rid of the extra category if you want?

**Comment by savente93** [comment]
Given that Jaap is very busy at the moment with GWW I'm going to just merge so we can move on. I want to use this in a couple of other PRs. if anything turns up we'll adjust down the line

**Comment by DirkEilander** [comment]
> Thanks! If I remember correctly, they were optional dependencies in a category called "all" which is why they are still optional now. I just didn't want to call it call because I thought that would be confusing with the `full` flavour. I'm happy to add them to the main dependencies, and just get rid of the extra category if you want?

There's one other thing to note. pyet is currently not distributed as a conda package, making it impossible to include it as a dependency in [our conda-forge recipe](https://github.com/conda-forge/hydromt-feedstock/blob/main/recipe/meta.yaml). Hence, for now I'd like to keep pyet as an optional dependency. The best solution here would be to contact the pyet developers teams and check I've they are open to distribute their package through e.g. conda-forge. I briefly discussed this with one of the main developers at EGU23 and he seemed open to it.

**Pull request merged**
