### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by savente93**
## Explanation
Apparently pydantic doesn't like you overriding the class vars of parents. As I think it is important to stay warning free, I added a pixi test job and a (non-required) ci job to make sure that the test suite remains warning free.  We can also always allow/ignore warnings that we think are acceptable in the `pyproject.toml` 

## General Checklist
- [x] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [ ] Updated documentation
- [ ] Updated changelog.rst

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Comment by Jaapel** [comment]
Regarding the pydantic thing, can we maybe change the class var annotation or update pydantic? It should be possible to inherit class vars according to: https://github.com/pydantic/pydantic/issues/2061

**Comment by savente93** [comment]
Nice I didn't see that one, I'll see if that works

**Comment by Jaapel** [comment]
Where do we use `supports_writing`? Otherwise try except NotImplementedError is also a valid way to check whether the driver supports writing

**Comment by savente93** [comment]
That's true, I just thought it was a bit nicer of a way to document it, but I guess we can also just remove it if you're okay with that.

**Review by Jaapel — APPROVED** [review]
I approve of my own changes 👍

**Pull request merged**
