### PR TITLE
Fix several raster issues related to memory

### LINKED ISSUE #350: BUG: Memory error when loading large raster datasets clipped to a geometry
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.   
- [X] I have checked that this bug exists on the main branch of HydroMT.            

### Issue Description

When loading a rasterdataset clipped with a geom we get memory errors for large datasets because of the `geometry_mask` in `raster.clip_geom` method, see [raster.py#L1157](https://github.com/Deltares/hydromt/blob/e4edd37a19f89bd99614782272864bad58527b27/hydromt/raster.py#L1157) With HydroMT-SFINCS we use many highres datasets which currently are impacted by this bug.

TODO
- [ ] Analyze what impact it has further downstream to remove the geometry_mask in `raster.clip_geom`.
- [ ] Use `clip_bbox` instead of `clip_geom` in the `RasterDatasetAdapter.get_data` method. The bbox can be calculated as `bbox = geom.to_crs(4326).total_bounds`.

### Reproducible Example

```
from hydromt import DataCatalog 
from shapely.geometry import box
import geopandas as gpd

bbox = [-90, 10, -70, 50]
gdf = gpd.GeoDataFrame(geometry=[box(*bbox)], crs=4326) 
cat = DataCatalog(r"deltares_data")
da0 = cat.get_rasterdataset("esa_worldcover", bbox=bbox) # no error
da1 = cat.get_rasterdataset("esa_worldcover", geom=gdf) # memory error
```

### Installed Versions

hydromt 0.7.1

### Additional context

_No response_

### LINKED ISSUE #435: clip datasets before repojecting to avoid memory issues
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Reprojecting a subarea of a larger dataset using reproject_like is not efficient as the whole extent is passes the method. 

### Current behaviour

Memory issues may arise

### Desired behaviour

Adding a clip_bbox step in reproject_like.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DirkEilander**
## Issue addressed
Fixes #435
Fixes #350 

## Explanation
- ``DataCatalog.get_rasterdataset`` always uses bbox to clip raster data. 
- ``raster.clip_geom`` only set a geometry mask if the mask argument is true to avoid memory issues. 
- ``raster.reproject_like`` first clips the data to the target extent before reprojecting. 

## Checklist
- [x] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [x] Updated documentation if needed
- [x] Updated changelog.rst if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Review by savente93 — APPROVED** [review]
Took the liberty of just removing the non-working pre-commit hook, as we discussed that we don't really need it. I can't really say much about the validity of the semantics (e.g. whether the transformations are correct) but the code looks good to me

**Comment by savente93** [comment]
Fixes #426

**Comment by DirkEilander** [comment]
> Took the liberty of just removing the non-working pre-commit hook, as we discussed that we don't really need it. I can't really say much about the validity of the semantics (e.g. whether the transformations are correct) but the code looks good to me

Should we also remove [.yamlfmt](https://github.com/Deltares/hydromt/blob/main/.yamlfmt) from the repos?

**Comment by savente93** [comment]
yes good one, I'd forgotten about that one.

**Pull request merged**
