### PR TITLE
Bugfix when using pyet method to calculate PET

### LINKED ISSUE #907: pyet gives error during pet calculation penman-monteith
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Using simple Penman-Monteith method to determine pet results in an error. pyet is used to calculate the actual vapor pressure. The wrong arguments are parsed to the pyet function or the wrong function is used. From the hydromt log:
```
2024-04-24 20:45:43,668 - update - forcing - INFO - Calculating Penman-Monteith ref evaporation
2024-04-24 20:45:43,683 - update - main - ERROR - calc_e0() got an unexpected keyword argument 'tmax'
Traceback (most recent call last):
  File "C:\Users\hartgrin\miniconda\envs\hydromt-wflow\Lib\site-packages\hydromt\cli\main.py", line 332, in update
    mod.update(model_out=model_out, opt=opt, forceful_overwrite=fo)
  File "C:\Users\hartgrin\miniconda\envs\hydromt-wflow\Lib\site-packages\hydromt\models\model_api.py", line 329, in update
    self._run_log_method(method, **kwargs)
  File "C:\Users\hartgrin\miniconda\envs\hydromt-wflow\Lib\site-packages\hydromt\models\model_api.py", line 188, in _run_log_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hartgrin\miniconda\envs\hydromt-wflow\Lib\site-packages\hydromt_wflow\wflow.py", line 2349, in setup_temp_pet_forcing
    pet_out = hydromt.workflows.forcing.pet(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hartgrin\miniconda\envs\hydromt-wflow\Lib\site-packages\hydromt\workflows\forcing.py", line 428, in pet
    pet_out = pm_fao56(
              ^^^^^^^^^
  File "C:\Users\hartgrin\miniconda\envs\hydromt-wflow\Lib\site-packages\hydromt\workflows\forcing.py", line 669, in pm_fao56
    avp = pyet.calc_e0(tmax=temp_max, tmin=temp_min, rh=temp_dew)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: calc_e0() got an unexpected keyword argument 'tmax'
```

And indeed, the following lines can be found in `forcing.py`:
```
    if var == "temp_dew":
        avp = pyet.calc_e0(tmean=temp_dew)
    elif var == "rh":
        avp = pyet.calc_e0(tmax=temp_max, tmin=temp_min, rh=temp_dew)
```
According to pyet documentation, `pyet.calc_e0` takes only `t_mean` as argument. But maybe it should be `pyet.calc_ea` which calculated the actual vapor pressure? That one also accepts multitple arguments, including `tmax, tmin, rh`. See also https://github.com/pyet-org/pyet/blob/ff411787fbaeaa903b9966e28df41db9afb05a28/pyet/meteo_utils.py#L222

Note: I tried this using pyet version 1.3.1, hydromt version 0.9.4 and hydront_wflow version 0.5.0

### Current behaviour

Gives an error when computing pet when not providing pressure term. The error is raised when pressure is calculated by pyet package

### Desired behaviour

Change arguments for pyet.calc_e0 or use pyet.calc_ea

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shartgring**
## Issue addressed
Fixes #907

## Explanation
Use ` pyet.calc_ea` instead of ` pyet.calc_e0` in PET workflow.

Note: The line `pyet.calc_ea(tmax=temp_max, tmin=temp_min, rh=temp_dew)` is still confusing as `rh` and `temp_dew` get mixed up (I got confused myself when submitting this PR, hence changing it to draft and back). However, the bug itself gets fixed and the changed code works without raising an error, contrary to the current code in main.

## Checklist
- [x] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [x] Updated documentation if needed
- [ ] Updated changelog.rst if needed
- [x] For predefined catalogs: update the catalog version in the file itself, the references in data/predefined_catalogs.yml, and the changelog in data/changelog.rst

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Review by savente93 — CHANGES_REQUESTED** [review]
Code change on its own looks good, and I'm glad to hear it works for you but there are a few things that I'd still like to see before merging:
1. can you add this to the change log under `Fixed`? A one line description of the fix and the PR number is sufficient. 
2. Would it be possible for you to produce a MWE or a test? I'm not quite sure what the problem was, but if this is something that only came up now I would like to see if we can make a test for it, so we don't regress. If you need help with this, feel free to ping me
3. it also seems that your PR only ran the lint workflows. Could you run the test suite too please?

Thanks!

**Comment by shartgring** [comment]
@savente93 yes will do! With regards to the tests, I will need to check if the artifact data contains all the necessary variables for the computation. If that is the case, I will include the test. Otherwise, I will let you know

**Comment by savente93** [comment]
@shartgring How's it going? anything I can help you with?

**Comment by savente93** [comment]
@shartgring Due to budget constraints, work on HydroMT will slow down for an unknown length of time, so if you want this to still be merged anytime soon, I'd suggest you try and get this PR merged asap. Feel free to contact me if you need help

**Comment by shartgring** [comment]
Yes! Ik probeer morgen of woensdag hier een paar uur voor te vinden. Ik laat het je weten of het lukt

Sebas

**Comment by shartgring** [comment]
Hi Sam! Sorry for getting back so late. I have updated the changelog in the docs.

For the testing, I am not sure why they did not work. I am working from a fork, can that be causing the problems? At least now I see that all tests are there (running now) so it seems that they are now all included.

About including a test case: I checked and there is already a PET test for the `penman-monteith_tdew` method, so I added one for 'penman-monteith_rh_simple`. Relative humidity is not provided by ERA5 so for the sake of testing, I converted it following dx.doi.org/10.1175/BAMS-86-2-225 (also clarified it in the code with a comment). Differences between tdew and rh results can be attributed to that simplified conversion step.

**Review by savente93 — APPROVED** [review]
failing test seems to be unrelated to this one, so the rest looks good to me

**Comment by savente93** [comment]
Could you run the pre-commit hooks before merging?

**Comment by shartgring** [comment]
Thanks! I got some help from Tjalling who explained the processes and also showed the dev guide with the checklist (https://deltares.github.io/hydromt/stable/dev/contributing.html#checklist-pull-requests). Should now all be ok!

Can you merge it? I have no write access on the hydromt repository

**Comment by savente93** [comment]
> Thanks! I got some help from Tjalling who explained the processes and also showed the dev guide with the checklist (https://deltares.github.io/hydromt/stable/dev/contributing.html#checklist-pull-requests). Should now all be ok!
> 
> Can you merge it? I have no write access on the hydromt repository

congrats on (what I think is) your first contribution! it's good that you mention you had to be shown the dev guide checklist, perhaps we should make that a bit more explicit at some point. I'll think it over. In any case, thanks!  🎉

**Pull request merged**
