### PR TITLE
restructure v1 package

### LINKED ISSUE #959: package structure and API
### Kind of request

Changing existing functionality

### Enhancement Description

I suggest to reorganize the package structure and API to make it more recognizable and easier to use for users and developers. 

At the highest level, the package structure should be organized around the main concepts of the package `DataCatalog` and `Model`, all submodules and scripts should in my opinion as much as possible be organized around these concepts in the `data_catalog` and `model` submodules. Additional submodules are `cli`, `gis`, `io`, `processes` (was workflows), `stats`, and `utils`.	 

**Suggested package structure:**

```bash
hydromt/
├── __init__.py # expose DataCatalog, Model
├── _compat.py
├── config.py
|── plugins.py  # TODO move to cli/ ?
├── _typing/
├── _utils/
│   ├── log.py # TODO this is used quite often in plugin examples, can be moved to utils?
├── _validators/
├── cli/
├── data_catalog/
│   ├── __init__.py  # expose DataCatalog, PredefinedCatalog
│   ├── predefined_catalogs.py
│   ├── data_catalog.py
|   ├── adapters/
|   |  ├── caching.py # TODO can be moved to _utils?
|   |  ├── utils.py # TODO has many unused functions; can be moved to _utils?
|   ├── sources/
|   ├── drivers/
|   ├── uri_resolvers/ 
├── gis/
├── io/
├── processes/ # NOTE: was workflows
├── model/ # NOTE: was models (plural)
│   ├── __init__.py  # expose Model, ModelComponent
│   ├── model.py
│   ├── root.py
│   ├── region.py  # NOTE: was workflows/region.py
│   ├── components/
├── stats/
├── utils/
```	

**remove scripts?**
hydromt/models/plugins.py -> this is superseded by plugins.py

### Use case

Easier structure for developers and users

### Additional Context

This also touches on some of the discussion in https://github.com/Deltares/hydromt/discussions/862

### PR DESCRIPTION
**Pull request by DirkEilander**
## Issue addressed
Fixes #959 

## Explanation
The package has been restructured as shown below. Some items to mention
- io methods from drivers (`read_raster` and `read_mfraster`) have been moved back to io. We keep these here as this functionality is partly shared by models for read/writing model data
- the `gis.utils` script has been split over `gis.gis_utils`, `gis.vector_utils` and `gis.raster_utils`
- `workflows` has been moved to `model.processes`
- `data_catalog` and `model` are singular as we define just one. `components`, `drivers`. `sources`, `adapters`, and `uri_resolvers` are plural as multiple are defined
- much less methods and classes are exposed at the highest level, this is now limited to `DataCatalog`, `Model`, `hydromt_step`, `PLUGINS`. 
- all internal functions in `_utils` start with `_`. This could also be extended to other internal API in `_typing`, `_validators`, etc
- The docs API have also been updated accordingly. 

```bash
hydromt/
├── __init__.py
├── _compat.py
├── config.py
├── plugins.py
├── _typing/
├── _utils/
├── _validators/
├── cli/
├── data_catalog/
│   ├── __init__.py
│   ├── predefined_catalogs.py
│   ├── data_catalog.py
│   ├── adapters/
│   ├── sources/
│   ├── drivers/
│   ├── uri_resolvers/ 
├── gis/
├── io/
├── model/
│   ├── __init__.py  
│   ├── model.py
│   ├── root.py
│   ├── hydromt_step.py
│   ├── components/
│   ├── processes/ 
├── stats/
├── utils/
```	

## General Checklist
- [ ] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [x] Updated documentation
- [ ] Updated changelog.rst

## Data/Catalog checklist
- [ ] `data/catalogs/predefined_catalogs.yml` has not been modified.
- [ ] None of the old `data_catalog.yml` files have been chagned
- [ ] `data/chagnelog.rst` has been updated
- [ ] new file uses `LF` line endings (done automatically if you used `update_versions.py`)
- [ ] New file has been tested locally
- [ ] Tests have been added using the new file in the test suite

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Comment by DirkEilander** [comment]
Some items are left todo:
- structure tests similar to package #976 
- update migration guide #977 
- rename MetaDataResolver class to UriResolver #

**Comment by savente93** [comment]
I'll try and review later this day

**Review by savente93 — APPROVED** [review]
I didn't review the code in depth since there are 184 files changed, but scrolling through I I see nothing objectionable. Feel free to merge once you fix the merge conflicts.

**Review by Jaapel — APPROVED** [review]
Looked at the merging commits at the end, LGMT 👍

**Pull request merged**
