### PR TITLE
update gpkg files to fgb in deltares_data catalog

### PR DESCRIPTION
**Pull request by DirkEilander**
issues with the GPKG files in a cloud environment seem to be fixed by using FlatGeoBuf instead. 

`ogr2ogr -f FlatGeobuf filename.fgb abc.shp`

- updated and checked default wflow data

TODO?:
- [x] update other gpkg data.

### CODE REVIEW

**Comment by Tjalling-dejong** [comment]
I wrote a script that converts all the gpkg and geojson files mentioned in the deltares data catalog. I first tested the script on one gpkg file:  river_atlas_v10.gpkg. 
The conversion resulted in a file size increase of 7.39 GB to 11.4 GB. In addition, the fgb file is unsorted when opened as a geodataframe. This makes it hard to assess if the gpkg and fgb data are equal. 

Furthermore, the river_atlas_v10.gpkg has multiple layers and when converted the fgb file cannot be read by fiona anymore. Reading fgb files would require pyogrio as an engine in geopandas.read_file.

**Comment by Tjalling-dejong** [comment]
At the moment a script is running on a horizon vm that converts all single layer geopackages or geojsons mentioned in the deltares data catalog.

The geopackages with multiple layers I skipped for now. We could convert the layers as seperate fgb files. @DirkEilander what are your thoughts on that?

The gpkg files with multiple layers:
- basin_atlas_v10.gpkg
- lake_atlas_v10.gpkg
- gadm36_levels.gpkg

**Comment by Tjalling-dejong** [comment]
The following files have been converted to flatgeobuf
p:\\wflow_global\\hydromt\\socio_economic\\gdp_world\\World_countries_GDPpcPPP.gpkg', 'p:\\wflow_global\\hydromt\\infrastructure\\grip\\GRIP4_world.gpkg', 'p:\\wflow_glow_global\\hydromt\\hydrography\\grwl\\GRWL_vector_V01.01\\grwl.gpkg', 'p:\\wflow_global\\hydromt\\hydrography\\grwl\\tindex.gpkg', 'p:\\wflow_global\\hydromt\\geogr\osm\aphy\\osm\\osm_coastlines-db.gpkg', 'p:\\wflow_global\\hydromt\\geography\\osm\\osm_landareas-db.gpkg', 'p:\\wflow_global\\hydromt\\geography\\wb\\WB_countries_Admin0.geojson'

**Comment by Tjalling-dejong** [comment]
I tested the new data catalog by building a wflow model. 
I ran into issues when I built a model for the Severn river near Gloucester, UK. This is the following error:

`OSError: [Errno -51] NetCDF: Unknown file format: 
b'p:\\wflow_global\\hydromt\\meteo\\era5_daily\\nc_merged\\era5_1975_daily.nc'` 

I tried building a model for the river Esk near Carlisle, UK. I got the same error again

I then tried to build a model in Italy and this time it worked.
This error could be unrelated to the changes I made. @DirkEilander what do you think?

**Comment by Tjalling-dejong** [comment]
The above mentioned issue is fixed when the zarr version of era5_daily is used. So no issues with the fgb files in the data catalog.

**Review by Tjalling-dejong — APPROVED** [review]

**Comment by DirkEilander** [comment]
fixes #282

**Pull request merged**
