### PR TITLE
Reeenable spacial dataset tests

### LINKED ISSUE #947: Enable integration tests in ` tests/components/test_spatialdatasets_component.py`
### Kind of request

None

### Enhancement Description

enable integration tests marked as skip or commented out in `tests/components/test_spatialdatasets_component.py` or add a further explanation why they can't be.

### Use case

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by savente93**
## Issue addressed
Fixes #947 

## Explanation
Explain how you addressed the bug/feature request, what choices you made and why.

## General Checklist
- [ ] Updated tests or added new tests
- [ ] Branch is up to date with `main`
- [ ] Tests & pre-commit hooks pass
- [ ] Updated documentation
- [ ] Updated changelog.rst

## Data/Catalog checklist
- [ ] `data/catalogs/predefined_catalogs.yml` has not been modified.
- [ ] None of the old `data_catalog.yml` files have been chagned
- [ ] `data/chagnelog.rst` has been updated
- [ ] new file uses `LF` line endings (done automatically if you used `update_versions.py`)
- [ ] New file has been tested locally
- [ ] Tests have been added using the new file in the test suite

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Comment by savente93** [comment]
updated a test data catalog. Test fails because the mask is outside of the data provided, so I'm suspecting this has to do with perhaps an incorrect projection. I'll come back to this later, of if anyone else thinks they know what is going feel free to commit to this branch

**Comment by savente93** [comment]
@DirkEilander I've tried to fix this but I'm having a lot of trouble and I suspect it will be a trivial change for someone that knows the data better. Could you help me with this? ( Hélène is on leave for the next 3 weeks)

**Comment by DirkEilander** [comment]
Hi @savente93. Sure, good you're reaching out! Must say that I also haven't worked on this part in the past, but will have a look and see what I can do. I don't have time today, but tomorrow or Thursday should work.

**Comment by savente93** [comment]
Thanks! Let me know if you have any questions, I'm happy to walk you through this, though the real issue is finding out why whatever mask we apply falls outside the data that is being passed in, once that's resolved, I can take it from there again if you want.

**Review by DirkEilander — APPROVED** [review]
LGTM!

**Pull request merged**
