### PR TITLE
Fix some documentation warnings and formatting issues

### LINKED ISSUE #371: DOC: fix small mistakes in developper doc code format
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Location of the documentation

https://deltares.github.io/hydromt/latest/dev/contributing.html#code-format

### Documentation problem

Link to pre-commit and first code block

image

### Suggested fix for documentation

Fix ink with _ at the end and fix code block indent

### PR DESCRIPTION
**Pull request by savente93**
Fixes #371 along with some other warnings generated when generating the docs that should help keep the docs clean. There are a few other warnings that still get generated that I haven't managed to address yet, which I would like to get back to at some point, but I figured it's better to just solve part of these things and move on to more urgent matters. Sorry for the huge number of files changed, but they are docstring changes only so hopefully it won't take too much time to review.

### CODE REVIEW

**Comment by savente93** [comment]
also Fixes #244

**Comment by savente93** [comment]
should also Fix #300

**Comment by savente93** [comment]
fixes #251

**Review by hboisgon — CHANGES_REQUESTED** [review]
Thanks for the changes @savente93 I corrected a few mistakes in a commit and added all developers in the team.

There is still one thing that is not fully fixed. In the pre-defined data catalog table now the indent looks good but the '/' in the path are now missing:
image

**Comment by hboisgon** [comment]
@savente93 do you think you could also adress #299 and #321 here?
They are also very small doc issues.

**Comment by savente93** [comment]
Something very strange is going on here. It is all generated correctly on my machine (see screenshot) 
image
Did you generate them locally? if so were there any relevant warnings?

**Comment by savente93** [comment]
Fixes #299 
Fixes #321

**Comment by hboisgon** [comment]
> Something very strange is going on here. It is all generated correctly on my machine (see screenshot) image Did you generate them locally? if so were there any relevant warnings?

Strange indeed. I generated the docs locally yes but don't remember any particular warning. Maybe Ubuntu vs Windows?

**Review by hboisgon — COMMENTED** [review]
Nice! I'll update the pictures and then just left is to figure out if we can why the data catalog tables prints differently. We generate the docs using Linux github actions so maybe not too urgent

**Comment by hboisgon** [comment]
Well also not fully clear to me which figures and I guess text modifications are needed. I'll let @DirkEilander change this directly

**Comment by savente93** [comment]
I've generated the docs both on linux and on windows and still cannot reproduce the problem. Can you pull the latest version and regenerate it in a new environment? sometimes code from older versions can make it's way into the docs because it was installed in conda

**Pull request merged**
