### PR TITLE
Add support for multiple csv segmented by var

### PR DESCRIPTION
**Pull request by savente93**
## Issue addressed
#453 

## Explanation
So I don't think this PR addresses an issue exactly, but it was something that I setup in #486 and wanted to finish anyway. I think it makes significant progress if not outright solve #453 (not totally sure which of the two it is, I'll leave that for the reviewer decide, or we can discuss it  during stadnup/refinement) and makes some additional progress towards #372. 

This simply adds the possibility for `open_mfcsv` to not only parse files per id, but also files per variables containing all ids (though not at the same time). The resulting dataset is the same as when the same data was segmented by id. I think it's a nice flexibility to have.
## Checklist
- [x] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [x] Updated documentation if needed
- [x] Updated changelog.rst if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

### CODE REVIEW

**Comment by savente93** [comment]
Makrking this as ready for review as the failure in the CI seems to happen after all the tests have passed. Possibly it's somehthing with the report generation. I'm investigating that seperately.

**Comment by savente93** [comment]
For posterities sake, the CIs crach with the following message: 

```
---------- coverage: platform linux, python 3.9.17-final-0 -----------
Coverage XML written to file coverage.xml

================= 143 passed, 65 warnings in 283.67s (0:04:43) =================
double free or corruption (!prev)
/home/runner/work/_temp/cb436074-82f6-48ae-bf0a-9afa0e4f349b.sh: line 1:  2714 Aborted                 (core dumped) python -m pytest --verbose --cov=hydromt --cov-report xml
```

**Comment by savente93** [comment]
note to self: add to doc index

**Review by Tjalling-dejong — APPROVED** [review]
LGTM 👍

**Pull request merged**
